### ISSUE TITLE
Crashes on second coin flip

### ISSUE THREAD

**Issue by dentych** [DemSquirrel/Le_Coinflip#2]
**What did I do?**
1. Open two browser and type in a name in both
2. Place bets
3. Wait for spin
4. Place new bets
5. Wait for spin
6. At second spin the node backend crashes

**Log output:**

```
le_coinflip@1.0.0 start /app
node index.js

listening on *:3000

Somebody connected
Somebody connected
Somebody connected
1499785628 asdf has connected
1499785628 Gave 300bits to asdf
1499785630 asdf2 has connected
1499785630 Gave 300bits to asdf2
1499785635 Removed 10bits from asdf2
1499785635 asdf2 placed a bet worth 10bits on the side 1
1499785638 Removed 21bits from asdf
1499785638 asdf placed a bet worth 21bits on the side 2
1
undefined
1499785653 Gave 20bits to asdf2
1499785678 Removed 50bits from asdf
1499785678 asdf placed a bet worth 50bits on the side 2
1
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './logs/logs1499785682.json'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at Object.saveLogs (/app/index.js:50:6)
    at Timeout._onTimeout (/app/index.js:199:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
npm info lifecycle le_coinflip@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! le_coinflip@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the le_coinflip@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-11T15_08_02_127Z-debug.log
```

**Comment by Admiral-Enigma** [comment]
This is because you need to manually create a folder called logs. I will put it in the install guide

**Comment by Admiral-Enigma** [comment]
Fixed it. Now if you still want the logs you have to create the folder and enable debug in index.js
